compiler warning: uninitialized variable
According to g++, there was a missing initialization:
/usr/include/c++/4.3/ext/new_allocator.h: In member function ‘void sysync::TODBCApiAgent::addSQLParameterMap(bool, bool, sysync::TParamMode, sysync::TItemField*, sysync::TDBFieldType)’:
/usr/include/c++/4.3/ext/new_allocator.h:108: error: ‘map.sysync::TParameterMap::outSiz’ may be used uninitialized in this function
src/DB_interfaces/odbc_db/odbcapiagent.cpp:1786: note: ‘map.sysync::TParameterMap::outSiz’ was declared here