syncsession.h: fix TDevInfResultsCommand::shrinkCommand()
In (probably mostly unused code?) the previous boolean result
of getIncomingState() was compared against the enum, which looks
wrong. Probably getIncomingState() was meant to return the enum.

gcc6 warned about this:
synccommand.cpp:4277:36: error: comparison of constant '1' with boolean
expression is always false [-Werror=bool-compare]
fSessionP->getIncomingState()>psta_init, // alerted only if init complete