TDebugLoggerBase::DebugOpenBlock: fixed build failure on Alpha CPU architecture
The code passes a NULL instead of va_list to DebugVOpenBlock.
On Alpha, va_list doesn't seem to be a pointer, so that fails:

sysync/debuglogger.cpp: In member function 'virtual void sysync::TDebugLoggerBase::DebugOpenBlock(const char*, const char*, bool)':
sysync/debuglogger.cpp:606: error: no matching function for call to 'sysync::TDebugLoggerBase::DebugVOpenBlock(const char*&, const char*&, bool&, NULL, NULL)'
sysync/debuglogger.h:271: note: candidates are: virtual void sysync::TDebugLoggerBase::DebugVOpenBlock(const char*, const char*, bool, const char*, va_list)

This patch passes a dummy va_list instance instead of NULL. Because
the corresponding format string is NULL, the value is never used,
so this doesn't change anything except getting the code to compile.

Reported as Debian Bug #544862.