DLL_interface: avoid undefined varg behavior
This fixes:

DLL_interface.cpp:187:19: error: passing an object that undergoes default
argument promotion to 'va_start'
      has undefined behavior [-Werror,-Wvarargs]
  va_start( args, aParamInfo ); // the element before the open param list

The fix works because bool can be converted to int (so old code still
works) while not being promoted (thus avoiding the undefined behavior).

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>