compiler warning: parenthesis in boolean expression
This fixes the following g++ warning:
syncsession.cpp:4257: error: suggest parentheses around && within ||

It's only a warning unless -Werror is used.